### PR TITLE
Install everything service automatically

### PR DESCRIPTION
**Pull request by jjw24**
Install everything service automatically

### CODE REVIEW

**Comment by taooceros** [comment]
what if user install Everything in somewhere else than default location?

**Comment by jjw24** [comment]
Hmm, is there a way to reliablely detect that it's installed?

**Comment by taooceros** [comment]
Not sure, let's check.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Flow-Launcher/Flow.Launcher.Plugin.Everything"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 晚上7:00
收件人:&nbsp;"Flow-Launcher/Flow.Launcher.Plugin.Everything"<Flow.Launcher.Plugin.Everything@noreply.github.com&gt;;
抄送:&nbsp;"天煞"<1569418337@qq.com&gt;;"Review requested"<review_requested@noreply.github.com&gt;;
主题:&nbsp;Re: [Flow-Launcher/Flow.Launcher.Plugin.Everything] Install everything service automatically (#6)





 
Hmm, is there a way to reliablely detect that it's installed?

**Comment by taooceros** [comment]
https://stackoverflow.com/questions/16379143/check-if-application-is-installed-in-registry
Somebody use registry to do that job.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Flow-Launcher/Flow.Launcher.Plugin.Everything"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 晚上7:00
收件人:&nbsp;"Flow-Launcher/Flow.Launcher.Plugin.Everything"<Flow.Launcher.Plugin.Everything@noreply.github.com&gt;;
抄送:&nbsp;"天煞"<1569418337@qq.com&gt;;"Review requested"<review_requested@noreply.github.com&gt;;
主题:&nbsp;Re: [Flow-Launcher/Flow.Launcher.Plugin.Everything] Install everything service automatically (#6)





 
Hmm, is there a way to reliablely detect that it's installed?

**Comment by jjw24** [comment]
@taooceros  done

**Comment by taooceros** [comment]
Seems great, but why not use the latest version of everything?

**Comment by jjw24** [comment]
yeah we can do that in the next iteration. I havent had a chance to look at how the api is integrated, this pr is just to get it auto installed.

**Pull request merged**
