### PR TITLE
Adjust Setting Panel Layout

### PR DESCRIPTION
**Pull request by onesounds**
- Adjust Setting Panel
- Remove Customize Explorer Code

### CODE REVIEW

**Comment by jjw24** [comment]
this depends on  https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything/pull/42 for the code to open file/folder via the api

**Comment by jjw24** [comment]
merging this in since this does not bump version, shouldnt create a new release. the other pr needs to be merged in for a new version release.

**Review by jjw24 — APPROVED** [review]

**Review by jjw24 — APPROVED** [review]

**Comment by jjw24** [comment]
my mistake, artifact for v1.5.6 release got overwritten with this change. Fixed by rerunning the workflow with code at v1.5.6 tag.

**Comment by taooceros** [comment]
> my mistake, artifact for v1.5.6 release got overwritten with this change. Fixed by rerunning the workflow with code at v1.5.6 tag.

They change the implementation? I remember when I tested it before, it won't create a new release 🤔

**Comment by jjw24** [comment]
it wont create the release but will overwrite the build artefact

**Pull request merged**
