### PR TITLE
Unicode Representation for Arrow

### PR DESCRIPTION
**Pull request by taooceros**
Let's see whether this can help with #55

### CODE REVIEW

**Comment by taooceros** [comment]
@VictoriousRaptor Let's see whether this may help😁

**Comment by VictoriousRaptor** [comment]
Haven't seen any update on crowdin so far. Is it supposed to be merged first to see updates?

**Comment by taooceros** [comment]
Let me see whether i can create a small branch in crowdin

**Comment by taooceros** [comment]
hm I don't have permission to do that so maybe we can just merge in. @jjw24 please give an approval😁

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
