### PR TITLE
Customize the Explorer setting

### PR DESCRIPTION
**Pull request by taooceros**

### CODE REVIEW

**Comment by taooceros** [comment]
The implementation of default argument for explorer.exe is a bit nasty......

**Comment by jjw24** [comment]
could we put "explorer" and "explorer.exe" as constants please, so next person that comes along wont accidentally spell it wrong somewhere

**Review by jjw24 — CHANGES_REQUESTED** [review]
please see comment

**Comment by kubalav** [comment]
@taooceros can you see on jjw24's comment? It would be nice to merge.

**Comment by taooceros** [comment]
Oh sorry, this message has been ignored by me.......I even unintentionally thought that this has been merged.....
I will take a look right now.

**Comment by taooceros** [comment]
Done, Thank you so much for reminding @kubalav 
@jjw24 would you please change the strings in EverythingSettings.xaml to dynamic resource? I am not sure how to do that. By simply moving them into en.xaml will block myself from compiling it....

**Comment by jjw24** [comment]
done will make a new release

**Pull request merged**
